### ISSUE TITLE
이미지 핸들러 커스텀 훅 제작

### ISSUE THREAD

**Issue by Gaoridang** [JSH99/Toy1_Team13#14]
## 의견
멘토님께서 말씀하신 대로 `feat/#14` 브랜치를 새로 파서 `URL.createObjectURL()`, `URL.revokeObjectURL()` 을 활용한 커스텀 훅을 제작하면 좋을 것 같습니다.

#14

**Comment by dbstjrals** [comment]
확인했습니당. 기능 구현후에 리팩토링 시간이 남으면 제작하겠습니다

**Comment by Gaoridang** [comment]
> 확인했습니당. 기능 구현후에 리팩토링 시간이 남으면 제작하겠습니다

헉 이슈 만들어 놓은걸 까먹고 있었네요😭 답변 주셔서 감사합니다!

**Comment by Sinary00** [comment]
#25 
@Gaoridang : useBlobUrl.ts 제작 완료
-> firebaseUtils uploadImage는 범용성 및 실용성이 좋지 않아 사용하지 않음.
